language: r
r:
  - oldrel
  - release
r_build_args: "--no-manual"
r_check_args: "--no-manual"
latex: false
warnings_are_errors: false
apt-packages:
  - build-essential 
  - libcurl4-gnutls-dev
  - libxml2-dev
  - libssl-dev
  - libgit2-dev
r_packages:
  - covr
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
