language: r
r:
  - oldrel
  - release
  - devel
warnings_are_errors: false
apt-packages:
  - build-essential 
  - libcurl4-gnutls-dev
  - libxml2-dev
  - libssl-dev
  - libgit2-dev
r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
