version: 2
jobs:
  build:
    docker:
      - image: rocker/tidyverse:4.0.3
    steps:
      - checkout
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - run:
          name: Install LaTeX
          command: R -e "tinytex::install_tinytex()"
      - run:
          name: Build package
          command: R CMD build --no-build-vignettes --no-manual .
      - run:
          name: Check package
          no_output_timeout: 240m
          command: R CMD check --no-build-vignettes --no-manual *tar.gz
      - run:
          name: Calculate code coverage
          no_output_timeout: 60m
          command: r -e 'covr::codecov()'
