version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:4.0.3
    steps:
      - checkout
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          no_output_timeout: 60m
          command: R CMD check *tar.gz
      - run:
          name: Calculate code coverage
          command: r -e 'covr::codecov()'
